version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "13:00"
      timezone: Europe/Berlin
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "build(deps)"
    open-pull-requests-limit: 15
    labels:
      - dependencies
    groups:
      formatting-linting-related:
        patterns:
          - "eslint"
          - "prettier"
          - "@commitlint/cli"
          - "sort-package-json"
          - "husky"
          - "lint-staged"
          - "@abinnovision/eslint*"
          - "@abinnovision/prettier*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "13:00"
      timezone: Europe/Berlin
    commit-message:
      prefix: "build(deps/gha)"
    open-pull-requests-limit: 5
    labels:
      - dependencies
