nodeLinker: node-modules

npmScopes:
  abinnovision:
    npmAlwaysAuth: false
    npmAuthToken: "${NPM_AUTH_TOKEN:-}"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://registry.yarnpkg.com https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
