name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.event.merge_group.id || 'main' }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}

permissions: {}

jobs:
  ci:
    name: CI
    uses: abinnovision/actions/.github/workflows/workflow.yaml@app-stack-v1
    permissions:
      contents: read
      packages: read
      actions: write
      id-token: write
    with:
      prerelease-channel: "beta"
      # There are no tests currently
      test-types: ""

  publish-npm:
    name: Publish npm
    needs: ci
    uses: abinnovision/actions/.github/workflows/workflow.yaml@publish-npm-v1
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      releases: ${{ needs.ci.outputs.releases }}
      npm: true
      ghpr: true
